apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-tailwind
spec:
  replicas: 2
  selector:
    matchLabels:
      app: master-tailwind
  template:
    metadata:
      labels:
        app: master-tailwind
    spec:
      containers:
      - name: master-tailwind
        image: gilsonrusso/master-tailwind:v2.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
