apiVersion: v1
kind: Service
metadata:
  name: master-tailwind-service
spec:
  selector:
    app: master-tailwind
  ports:
    - name: tailwind-service
      protocol: TCP
      port: 80
      targetPort: 3000
