name: Pipeline CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.12.2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dockerfile Analysis
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile

      - name: Docker Build Image
        run: |
          docker build -t gilsonrusso/master-tailwind:v${{ github.run_number }} -f Dockerfile .
          docker build -t gilsonrusso/master-tailwind:latest -f Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            gilsonrusso/master-tailwind:v${{ github.run_number }}
            gilsonrusso/master-tailwind:latest

  deploy:
    name: Deploy to GitHub
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Deploy Repository
        uses: actions/checkout@v4
        with:
          repository: gilsonrusso/k8s-argocd-master-tailwind
          token: ${{ secrets.PAT_TOKEN }}
          path: repo-deploy
          ref: main

      - name: Display Deployment File Before Update
        working-directory: repo-deploy
        run: cat k8s/deployment.yaml

      - name: List Files in Repo
        run: ls -R repo-deploy

      - name: Update Image in K8s Manifest
        working-directory: repo-deploy
        run: |
          sed -i 's|image: "gilsonrusso/master-tailwind:.*"|image: "gilsonrusso/master-tailwind:latest"|' k8s/deployment.yaml
          cat k8s/deployment.yaml

      - name: Check Git Status
        working-directory: repo-deploy
        run: git status

      - name: Commit and Push Updates
        working-directory: repo-deploy
        run: |
          git config --global user.email "${{ github.actor }}+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update of Image to v${{ github.run_number }}"
          git push origin main
