name: Pipeline CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.12.2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Build Image
        run: |
          docker build -t gilsonrusso/master-tailwind:latest -f Dockerfile.prod .

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Dockerfile Analysis
        uses: hadolint/handolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile.prod

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            gilsonrusso/master-tailwind:v${{ github.run_number }}
            gilsonrusso/master-tailwind:latest
          context: .
          file: ./DockerFile.prod
  deploy:
    name: Deploy to GitHub
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Checkout Deploy Repository
        uses: actions/checkout@v4
        with:
          repositrory: gilsonrusso/k8s-argocd-master-tailwind
          token: ${{ secret.PAT_TOKEN }}
          path: repo-deploy
          ref: main

      - name: Update a Image on Manifast K8S
        run: |
          sed -i 's|image': gilsonrusso/master-tailwind.*|image: gilsonrusso/master-tailwind:latest'
      
      - name: Commit and Push Updated
        working-directory: repo-deploy
        run: |
          git config --global user.email "gilsonrusso@outlook.com"
          git config --global user.name "Gilson Russo"
          git add .
          git commit -m "Update of Image to v${{ github.run_number }}"
          git push origin main
