name: Pipeline CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.11.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dockerfile Analysis
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile

      - name: Docker Build Image
        run: |
          docker build -t gilsonrusso/master-tailwind:v${{ github.run_number }} -f Dockerfile .
          docker build -t gilsonrusso/master-tailwind:latest -f Dockerfile .

      - name: Push Image to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push gilsonrusso/master-tailwind:v${{ github.run_number }}
          docker push gilsonrusso/master-tailwind:latest
  deploy:
    name: Deploy to GitHub
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Checkout Deploy Repository
        uses: actions/checkout@v4
        with:
          repository: gilsonrusso/k8s-argocd-master-tailwind
          token: ${{ secrets.PAT_TOKEN }}
          path: repo-deploy
          ref: main

      - name: Update a Image on Manifast K8S
        run: |
          sed -i 's|image': gilsonrusso/master-tailwind.*|image: gilsonrusso/master-tailwind:latest'

      - name: Commit and Push Updated
        working-directory: repo-deploy
        run: |
          git config --global user.email "${{ github.actor_id }}+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update of Image to v${{ github.run_number }}"
          git push origin main
